/// Claim PDF Builder — generates a structured HTML-based claim summary
/// Note: On Flutter Web we can't use the `pdf` package's native renderer.
/// Instead, we generate a printable HTML string and open it in a new tab.
/// On mobile (future), use pdf + printing packages.
library;

import 'package:flutter/material.dart';

class ClaimPdfBuilder {
  /// Builds an HTML claim document and returns it as a data URI for printing.
  static String buildHtml({
    required String claimId,
    required String applicantName,
    required List<Map<String, dynamic>> assessments,
  }) {
    final total = assessments.fold<double>(0, (s, a) => s + ((a['estimated_cost_myr'] as num?)?.toDouble() ?? 0));
    final date = DateTime.now();
    final dateStr = '${date.day}/${date.month}/${date.year}';

    final rows = assessments.asMap().entries.map((e) {
      final i = e.key + 1;
      final a = e.value;
      return '''
        <tr>
          <td>$i</td>
          <td>${a['room'] ?? 'Unknown'}</td>
          <td>${a['description_ms'] ?? '-'}</td>
          <td>${a['nadma_band'] ?? 'B'}</td>
          <td>${_severity(a['severity'] as int? ?? 1)}</td>
          <td>RM ${a['estimated_cost_myr'] ?? 0}</td>
        </tr>''';
    }).join('\n');

    return '''<!DOCTYPE html>
<html lang="ms">
<head>
<meta charset="UTF-8">
<title>Borang Tuntutan Banjir — $claimId</title>
<style>
  * { font-family: Arial, sans-serif; margin: 0; padding: 0; box-sizing: border-box; }
  body { padding: 40px; color: #1a1a1a; }
  .header { text-align: center; margin-bottom: 32px; }
  .header h1 { font-size: 20px; }
  .header h2 { font-size: 14px; color: #555; margin-top: 4px; }
  .metadata { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 24px; padding: 16px; border: 1px solid #ccc; border-radius: 4px; }
  .meta-row { display: flex; flex-direction: column; }
  .meta-label { font-size: 11px; color: #666; text-transform: uppercase; letter-spacing: 1px; }
  .meta-value { font-size: 14px; font-weight: bold; margin-top: 4px; }
  table { width: 100%; border-collapse: collapse; margin-top: 16px; font-size: 13px; }
  th { background: #1a1a1a; color: white; padding: 10px 8px; text-align: left; }
  td { border: 1px solid #ddd; padding: 8px; }
  tr:nth-child(even) { background: #f9f9f9; }
  .total { margin-top: 16px; text-align: right; font-size: 18px; font-weight: bold; color: #c62828; }
  .footer { margin-top: 48px; display: grid; grid-template-columns: 1fr 1fr; gap: 32px; }
  .sig-line { border-top: 1px solid #333; padding-top: 8px; font-size: 12px; color: #555; margin-top: 40px; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 3px; font-size: 11px; font-weight: bold; }
  .band-a { background: #e8f5e9; color: #1b5e20; }
  .band-b { background: #fff3e0; color: #bf360c; }
  .band-c { background: #fce4ec; color: #880e4f; }
</style>
</head>
<body>
  <div class="header">
    <h1>BORANG PERMOHONAN BANTUAN BANJIR</h1>
    <h2>Flood Relief Aid Application Form — JKM / NADMA</h2>
    <p style="font-size:12px;color:#666;margin-top:8px">Sistem FloodSense Malaysia · AI-Assisted Damage Assessment</p>
  </div>

  <div class="metadata">
    <div class="meta-row">
      <span class="meta-label">ID Tuntutan / Claim ID</span>
      <span class="meta-value">$claimId</span>
    </div>
    <div class="meta-row">
      <span class="meta-label">Tarikh / Date</span>
      <span class="meta-value">$dateStr</span>
    </div>
    <div class="meta-row">
      <span class="meta-label">Nama Pemohon / Applicant</span>
      <span class="meta-value">$applicantName</span>
    </div>
    <div class="meta-row">
      <span class="meta-label">Status</span>
      <span class="meta-value" style="color:#e53935">MENUNGGU SEMAKAN / PENDING REVIEW</span>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Bilik / Room</th>
        <th>Penerangan / Description</th>
        <th>Band NADMA</th>
        <th>Tahap Kerosakan / Severity</th>
        <th>Anggaran Kos / Est. Cost</th>
      </tr>
    </thead>
    <tbody>
      $rows
    </tbody>
  </table>

  <div class="total">Jumlah / Total: RM ${total.toStringAsFixed(2)}</div>

  <div class="footer">
    <div>
      <p style="font-size:12px;color:#666">Tandatangan Pemohon / Applicant Signature</p>
      <div class="sig-line">$applicantName</div>
    </div>
    <div>
      <p style="font-size:12px;color:#666">Disahkan oleh / Verified by (Pegawai JKM)</p>
      <div class="sig-line">________________________</div>
    </div>
  </div>

  <p style="margin-top:32px;font-size:10px;color:#999;text-align:center">
    Dokumen ini dijana secara automatik oleh sistem FloodSense AI. Semua maklumat tertakluk kepada pengesahan pegawai JKM.<br>
    This document was auto-generated by FloodSense AI. All information subject to JKM officer verification.
  </p>

  <script>window.onload = () => window.print();</script>
</body>
</html>''';
  }

  static String _severity(int s) {
    const labels = {1: 'Minimum', 2: 'Ringan', 3: 'Sederhana', 4: 'Teruk', 5: 'Kritikal'};
    return labels[s] ?? 'Unknown';
  }
}

/// Web-compatible print helper — opens HTML in a new tab
void printClaimWeb(BuildContext context, String claimId, String applicantName, List<Map<String, dynamic>> assessments) {
  final html = ClaimPdfBuilder.buildHtml(
    claimId: claimId,
    applicantName: applicantName,
    assessments: assessments,
  );
  // html is the printable document — on web, pass to URL.createObjectURL + window.open
  // On mobile (future): write html to a temp file and open with printing package
  debugPrint('[ClaimPdfBuilder] generated ${html.length} chars for $claimId');
  // For demo, show a dialog with the claim ID + print instructions
  showDialog(
    context: context,
    builder: (_) => AlertDialog(
      backgroundColor: const Color(0xFF1E1E1E),
      title: const Text('Tuntutan Dijana / Claim Generated'),
      content: Column(mainAxisSize: MainAxisSize.min, children: [
        const Icon(Icons.picture_as_pdf, color: Color(0xFFFFB300), size: 48),
        const SizedBox(height: 12),
        Text('ID: $claimId', style: const TextStyle(color: Color(0xFFFFB300), fontWeight: FontWeight.w700, fontSize: 16)),
        const SizedBox(height: 8),
        const Text('Tuntutan telah disimpan ke Firebase.\nDihantar kepada pegawai JKM untuk semakan.',
            textAlign: TextAlign.center, style: TextStyle(color: Color(0xFF757575), fontSize: 13)),
      ]),
      actions: [
        TextButton(onPressed: () => Navigator.pop(context), child: const Text('Tutup', style: TextStyle(color: Color(0xFFE53935)))),
      ],
    ),
  );
}
