import 'dart:async';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../core/providers/locale_provider.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';
import 'package:geolocator/geolocator.dart';
import '../../../core/theme/app_theme.dart';
import 'volunteer_repository.dart';
import '../../core/widgets/loc_text.dart';

/// Shown after a volunteer taps ACCEPT on a mission offer.
/// Light-theme design with an embedded map showing the route to the victim.
class MissionDispatchScreen extends StatefulWidget {
  final String missionId;
  final Map<String, dynamic> data;
  const MissionDispatchScreen({super.key, required this.missionId, required this.data});

  @override
  State<MissionDispatchScreen> createState() => _MissionDispatchScreenState();
}

class _MissionDispatchScreenState extends State<MissionDispatchScreen> {
  final _repo = VolunteerRepository();
  bool _completing = false;
  int _missionStep = 0; // 0 = Accepted, 1 = Arrived
  Timer? _localTimer;
  Duration _elapsed = Duration.zero;
  StreamSubscription<QuerySnapshot>? _incidentSub;
  StreamSubscription<Position>? _gpsSub;

  @override
  void initState() {
    super.initState();
    _startLocalTimer();
    _accept();
    _listenToCancellation();
    _startGPSStream();
  }

  void _startGPSStream() {
    _gpsSub = Geolocator.getPositionStream(
      locationSettings: const LocationSettings(
        accuracy: LocationAccuracy.high,
        distanceFilter: 3, // Update every 3 meters
      ),
    ).listen((pos) async {
      final sosId = widget.data['sos_id'] as String? ?? '';
      if (sosId.isEmpty || !mounted) return;
      
      try {
        final querySnap = await FirebaseFirestore.instance
            .collection('incidents')
            .where('sos_id', isEqualTo: sosId)
            .get();
        for (var doc in querySnap.docs) {
          await doc.reference.update({
            'rescuer_lat': pos.latitude,
            'rescuer_lng': pos.longitude,
            'rescuer_heading': pos.heading,
          });
        }
      } catch (e) {
        debugPrint('[MissionDispatch] GPS stream update error: $e');
      }
    });
  }

  void _listenToCancellation() {
    final sosId = widget.data['sos_id'] as String? ?? '';
    if (sosId.isNotEmpty) {
      _incidentSub = FirebaseFirestore.instance
          .collection('incidents')
          .where('sos_id', isEqualTo: sosId)
          .snapshots()
          .listen((snap) {
        if (snap.docs.isNotEmpty) {
          final data = snap.docs.first.data();
          final status = data['status'] as String?;
          if (status == 'CANCELLED') {
            _showCancelledAlert();
          }
        }
      });
    }
  }

  void _showCancelledAlert() {
    if (!mounted) return;
    _incidentSub?.cancel();
    _localTimer?.cancel();
    showDialog<void>(
      context: context,
      barrierDismissible: false,
      builder: (ctx) => AlertDialog(
        title: const LocText('Misi Dibatalkan', 'Mission Cancelled', style: TextStyle(color: AppTheme.emergency)),
        content: const LocText(
            'Mangsa telah membatalkan permohonan SOS ini.',
            'The victim has cancelled this SOS request.'),
        actions: [
          FilledButton(
            onPressed: () {
              Navigator.pop(ctx);
              Navigator.pop(context); // close dispatch screen
            },
            style: FilledButton.styleFrom(backgroundColor: AppTheme.emergency),
            child: const LocText('Tutup', 'Close'),
          ),
        ],
      ),
    );
  }

  void _startLocalTimer() {
    _localTimer = Timer.periodic(const Duration(seconds: 1), (t) {
      if (mounted) setState(() => _elapsed += const Duration(seconds: 1));
    });
  }

  @override
  void dispose() {
    _localTimer?.cancel();
    _incidentSub?.cancel();
    _gpsSub?.cancel();
    super.dispose();
  }

  Future<void> _accept() async {
    await _repo.respondToMission(
      widget.missionId,
      'ACCEPTED',
      widget.data['sos_id'] as String? ?? '',
    );
  }

  Future<void> _markComplete() async {
    setState(() => _completing = true);
    try {
      final sosId = widget.data['sos_id'] as String? ?? '';
      
      // Update mission offer if it exists
      await FirebaseFirestore.instance.collection('mission_offers').doc(widget.missionId).update({'status': 'COMPLETED'}).catchError((_) {});
      
      // The incident document ID is uniquely generated by Firestore, while sosId is a field. We must query by field.
      if (sosId.isNotEmpty) {
        final querySnap = await FirebaseFirestore.instance
            .collection('incidents')
            .where('sos_id', isEqualTo: sosId)
            .get();
        for (var doc in querySnap.docs) {
          await doc.reference.update({'status': 'RESCUED'});
        }
      }
      _localTimer?.cancel();
      _gpsSub?.cancel();
      if (mounted) {
        setState(() => _missionStep = 2);
        
        await showDialog<void>(
          context: context,
          barrierDismissible: false,
          builder: (dialogCtx) => AlertDialog(
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(18)),
            contentPadding: const EdgeInsets.fromLTRB(24, 24, 24, 16),
            content: Column(mainAxisSize: MainAxisSize.min, children: [
              Container(
                width: 56, height: 56,
                decoration: const BoxDecoration(color: AppTheme.hopeLight, shape: BoxShape.circle),
                child: const Icon(Icons.check_circle_outline, color: AppTheme.hope, size: 32),
              ),
              const SizedBox(height: 16),
              const LocText(
                'Misi Selesai!',
                'Mission Completed!',
                style: TextStyle(fontWeight: FontWeight.w800, fontSize: 18, color: Colors.black),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 8),
              const LocText(
                'Terima kasih atas bantuan anda. Laporan telah direkodkan. Sila maklumkan kepada komander operasi di lapangan.',
                'Thank you for your assistance. The report has been recorded. Please notify the field operations commander.',
                style: TextStyle(color: Color(0xFF4B5563), fontSize: 13, height: 1.5),
                textAlign: TextAlign.center,
              ),
            ]),
            actions: [
              SizedBox(
                width: double.infinity,
                child: FilledButton(
                  onPressed: () => Navigator.of(dialogCtx).pop(),
                  style: FilledButton.styleFrom(
                    backgroundColor: AppTheme.hope,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                    padding: const EdgeInsets.symmetric(vertical: 14),
                  ),
                  child: const LocText('Kembali ke Dashboard', 'Return to Dashboard', style: TextStyle(fontWeight: FontWeight.w700)),
                ),
              ),
            ],
          ),
        );
        if (mounted) Navigator.pop(context);
      }
    } finally {
      if (mounted) setState(() => _completing = false);
    }
  }

  Future<void> _requestBackup() async {
    showDialog<void>(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const LocText('Bantuan Tambahan Diminta', 'Backup Requested', style: TextStyle(color: AppTheme.emergency)),
        content: const LocText(
            'Notifikasi kecemasan telah dihantar kepada APM dan sukarelawan berdekatan.\n\nSila pastikan keselamatan anda terjamin. Bertahan di lokasi.',
            'Emergency notification has been sent to APM and nearby volunteers.\n\nPlease ensure your safety is guaranteed. Hold your position.'),
        actions: [
          FilledButton(
            onPressed: () => Navigator.pop(ctx),
            style: FilledButton.styleFrom(backgroundColor: AppTheme.emergency),
            child: const LocText('Tutup', 'Close'),
          ),
        ],
      ),
    );
    try {
      final sosId = widget.data['sos_id'] as String? ?? '';
      if (sosId.isNotEmpty) {
        final querySnap = await FirebaseFirestore.instance.collection('incidents').where('sos_id', isEqualTo: sosId).get();
        for (var doc in querySnap.docs) {
           doc.reference.update({'urgency': 'CRITICAL', 'backup_requested': true});
        }
      }
    } catch (_) {}
  }

  Future<void> _nextStep() async {
    if (_missionStep == 0) {
      if (mounted) setState(() => _missionStep = 1);
    } else {
      await _markComplete();
    }
  }

  @override
  Widget build(BuildContext context) {
    final isMs = context.watch<LocaleProvider>().locale.languageCode == 'ms';
    final elapsed = _elapsed;
    final m = elapsed.inMinutes.remainder(60).toString().padLeft(2, '0');
    final s = elapsed.inSeconds.remainder(60).toString().padLeft(2, '0');
    final elapsedStr = '${elapsed.inHours > 0 ? '${elapsed.inHours}:' : ''}$m:$s';

    final address = widget.data['address'] as String? ?? 'Unknown';
    final headCount = widget.data['head_count'] ?? '?';
    final vulnerable = (widget.data['vulnerable'] as List?)?.cast<String>() ?? [];
    // Victim location from Firestore or demo fallback
    final lat = (widget.data['lat'] as num?)?.toDouble() ?? 3.0738;
    final lng = (widget.data['lng'] as num?)?.toDouble() ?? 101.5183;
    final victimPin = LatLng(lat, lng);
    // Volunteer is slightly offset (would be real GPS in production)
    final volunteerPin = LatLng(lat + 0.012, lng - 0.008);

    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: const LocText('Misi Aktif', 'Active Mission',
            style: TextStyle(color: Colors.black, fontWeight: FontWeight.w700)),
        backgroundColor: Colors.white,
        foregroundColor: Colors.black,
        elevation: 0,
        surfaceTintColor: Colors.transparent,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Colors.black),
          onPressed: () => Navigator.pop(context),
        ),
        bottom: const PreferredSize(
          preferredSize: Size.fromHeight(1),
          child: Divider(height: 1, color: AppTheme.border),
        ),
      ),
      body: Column(children: [
        // ── Timer banner ─────────────────────────────────────────────────────
        Container(
          width: double.infinity,
          padding: const EdgeInsets.symmetric(vertical: 12),
          color: AppTheme.emergencyLight,
          child: Column(children: [
            const LocText('MASA BERLALU', 'TIME ELAPSED',
                style: TextStyle(color: AppTheme.textMuted, fontSize: 11, letterSpacing: 1.5)),
            const SizedBox(height: 4),
            Text(elapsedStr,
                style: const TextStyle(
                    fontSize: 36,
                    fontWeight: FontWeight.w900,
                    color: AppTheme.emergency,
                    fontFeatures: [FontFeature.tabularFigures()])),
          ]),
        ),

        Expanded(
          child: ListView(padding: const EdgeInsets.all(20), children: [

            // ── Embedded Navigation Map ──────────────────────────────────────
            _sectionLabel(isMs ? 'PETA LALUAN' : 'ROUTE MAP'),
            const SizedBox(height: 8),
            ClipRRect(
              borderRadius: BorderRadius.circular(16),
              child: SizedBox(
                height: 200,
                child: FlutterMap(
                  options: MapOptions(
                    initialCenter: LatLng(
                      (victimPin.latitude + volunteerPin.latitude) / 2,
                      (victimPin.longitude + volunteerPin.longitude) / 2,
                    ),
                    initialZoom: 13,
                  ),
                  children: [
                    TileLayer(
                      urlTemplate: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
                      userAgentPackageName: 'com.floodsense.floodsense',
                    ),
                    PolylineLayer(polylines: [
                      Polyline(
                        points: [volunteerPin, victimPin],
                        color: AppTheme.govBlue,
                        strokeWidth: 4,
                      ),
                    ]),
                    MarkerLayer(markers: [
                      Marker(
                        point: victimPin,
                        width: 44, height: 44,
                        child: const Icon(Icons.location_pin, color: AppTheme.emergency, size: 44),
                      ),
                      Marker(
                        point: volunteerPin,
                        width: 40, height: 40,
                        child: const Icon(Icons.directions_run, color: AppTheme.govBlue, size: 36),
                      ),
                    ]),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 20),

            // ── Location ─────────────────────────────────────────────────────
            _sectionLabel(isMs ? 'LOKASI' : 'LOCATION'),
            const SizedBox(height: 8),
            _infoCard(icon: Icons.location_on, color: AppTheme.emergency, label: address),
            const SizedBox(height: 16),

            // ── Victims ──────────────────────────────────────────────────────
            _sectionLabel(isMs ? 'MANGSA' : 'VICTIMS'),
            const SizedBox(height: 8),
            _infoCard(icon: Icons.people, color: AppTheme.warning, label: isMs ? '$headCount orang' : '$headCount people'),
            if (vulnerable.isNotEmpty) ...[
              const SizedBox(height: 8),
              Wrap(spacing: 8, runSpacing: 6, children: vulnerable.map((g) => Container(
                padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                decoration: BoxDecoration(
                    color: AppTheme.warningLight,
                    borderRadius: BorderRadius.circular(20),
                    border: Border.all(color: AppTheme.warning.withAlpha(80))),
                child: Text(g, style: const TextStyle(color: AppTheme.warning, fontSize: 12, fontWeight: FontWeight.w600)),
              )).toList()),
            ],
            const SizedBox(height: 16),

            // ── Status ───────────────────────────────────────────────────────
            _sectionLabel(isMs ? 'STATUS OPERASI' : 'OPERATION STATUS'),
            const SizedBox(height: 8),
            _buildMissionStepper(),
            const SizedBox(height: 20),

            // ── Notes ────────────────────────────────────────────────────────
            _sectionLabel(isMs ? 'CATATAN PENTING' : 'IMPORTANT NOTES'),
            const SizedBox(height: 8),
            ...(isMs ? [
                    'Pakai jaket keselamatan',
                    'Hubungi 999 jika perlu sokongan tambahan',
                    'Rakam video pendek sebagai bukti',
                ] : [
                    'Wear safety jacket',
                    'Call 999 if backup needed',
                    'Record short video as proof',
                ]).map((t) => Padding(
              padding: const EdgeInsets.only(bottom: 10),
              child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
                const Icon(Icons.chevron_right, color: AppTheme.govBlue, size: 18),
                const SizedBox(width: 4),
                Expanded(child: Text(t, style: const TextStyle(color: AppTheme.textSecondary, fontSize: 13))),
              ]),
            )),
          ]),
        ),

        // ── Action button ──────────────────────────────────────────────────
        Padding(
          padding: const EdgeInsets.fromLTRB(20, 0, 20, 20),
          child: Column(
            children: [
              SizedBox(
                width: double.infinity,
                height: 56,
                child: ElevatedButton.icon(
                  onPressed: _completing ? null : _nextStep,
                  icon: _completing
                      ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white))
                      : Icon(_missionStep == 0 ? Icons.directions_car : Icons.check_circle),
                  label: Text(_missionStep == 0 
                      ? (isMs ? 'SAYA TELAH TIBA' : 'I HAVE ARRIVED') 
                      : (isMs ? 'MISI SELESAI' : 'MISSION COMPLETE'),
                      style: const TextStyle(fontWeight: FontWeight.w700, fontSize: 13)),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: _missionStep == 0 ? AppTheme.govBlue : AppTheme.hope,
                    foregroundColor: Colors.white,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
                  ),
                ),
              ),
              const SizedBox(height: 12),
              SizedBox(
                width: double.infinity,
                child: TextButton.icon(
                  onPressed: _requestBackup,
                  icon: const Icon(Icons.group_add, size: 20),
                  label: const LocText('Minta Bantuan', 'Request Backup', style: TextStyle(fontWeight: FontWeight.w700)),
                  style: TextButton.styleFrom(foregroundColor: AppTheme.emergency),
                ),
              ),
            ],
          ),
        ),
      ]),
    );
  }

  Widget _sectionLabel(String t) => Text(t,
      style: const TextStyle(color: AppTheme.textMuted, fontSize: 11, letterSpacing: 1.5, fontWeight: FontWeight.w600));

  Widget _infoCard({required IconData icon, required Color color, required String label}) => Container(
    padding: const EdgeInsets.all(14),
    decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: AppTheme.border)),
    child: Row(children: [
      Icon(icon, color: color, size: 20),
      const SizedBox(width: 12),
      Expanded(child: Text(label, style: const TextStyle(color: Colors.black, fontWeight: FontWeight.w600, fontSize: 14))),
    ]),
  );

  Widget _buildMissionStepper() {
    final isMs = context.watch<LocaleProvider>().locale.languageCode == 'ms';
    final stepsMs = [
      (Icons.radar, 'Misi Diterima', 'Menuju ke lokasi mangsa'),
      (Icons.location_on, 'Tiba di Lokasi', 'Menyelamat & menilai keadaan'),
      (Icons.check_circle, 'Misi Selesai', 'Laporan sedia dihantar'),
    ];
    final stepsEn = [
      (Icons.radar, 'Mission Accepted', 'Heading to victim location'),
      (Icons.location_on, 'Arrived at Location', 'Rescuing & assessing situation'),
      (Icons.check_circle, 'Mission Completed', 'Report ready to be sent'),
    ];
    final steps = isMs ? stepsMs : stepsEn;

    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(12),
          border: Border.all(color: AppTheme.border)),
      child: Column(
        children: List.generate(steps.length, (i) {
          final isActive = i <= _missionStep;
          final isCurrent = i == _missionStep;
          final isDone = i < _missionStep;

          return Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
            Column(children: [
              CircleAvatar(
                radius: 12,
                backgroundColor: isActive ? AppTheme.hope : AppTheme.border,
                child: Icon(isDone ? Icons.check : steps[i].$1, color: Colors.white, size: 12),
              ),
              if (i < 2)
                Container(
                  width: 2, height: 28,
                  color: isActive ? AppTheme.hope.withAlpha(80) : AppTheme.border,
                ),
            ]),
            const SizedBox(width: 12),
            Expanded(
              child: Padding(
                padding: const EdgeInsets.only(top: 2, bottom: 8),
                child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                  Text(steps[i].$2, style: TextStyle(
                      color: isActive ? Colors.black : AppTheme.textSecondary,
                      fontWeight: isCurrent ? FontWeight.w800 : FontWeight.w600, fontSize: 13)),
                  Text(steps[i].$3, style: const TextStyle(
                      color: AppTheme.textSecondary,
                      fontSize: 11)),
                ]),
              ),
            ),
          ]);
        }),
      ),
    );
  }
}
